<?php

namespace Database\Factories;

use App\Models\Announcement;
use App\Models\Journal;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Announcement>
 */
class AnnouncementFactory extends Factory
{
    protected $model = Announcement::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $isPublished = fake()->boolean(70);
        $publishedAt = $isPublished ? fake()->dateTimeBetween('-1 year', 'now') : null;

        return [
            'journal_id' => Journal::factory(),
            'user_id' => User::factory(),
            'title' => fake()->sentence(fake()->numberBetween(4, 10)),
            'slug' => null, // Will be auto-generated by sluggable trait
            'content' => fake()->paragraphs(fake()->numberBetween(2, 5), true),
            'excerpt' => fake()->boolean(60) ? fake()->paragraph() : null,
            'type' => fake()->randomElement(array_keys(Announcement::TYPES)),
            'is_pinned' => fake()->boolean(15),
            'is_published' => $isPublished,
            'published_at' => $publishedAt,
            'expires_at' => fake()->boolean(30) ? fake()->dateTimeBetween('+1 week', '+6 months') : null,
        ];
    }

    /**
     * Indicate that the announcement is published.
     */
    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => true,
            'published_at' => fake()->dateTimeBetween('-6 months', 'now'),
        ]);
    }

    /**
     * Indicate that the announcement is a draft.
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => false,
            'published_at' => null,
        ]);
    }

    /**
     * Indicate that the announcement is pinned.
     */
    public function pinned(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_pinned' => true,
        ]);
    }

    /**
     * Indicate that the announcement has expired.
     */
    public function expired(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => true,
            'published_at' => fake()->dateTimeBetween('-1 year', '-3 months'),
            'expires_at' => fake()->dateTimeBetween('-2 months', '-1 day'),
        ]);
    }

    /**
     * Set a specific announcement type.
     */
    public function ofType(string $type): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => $type,
        ]);
    }

    /**
     * Create a call for papers announcement.
     */
    public function callForPapers(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => Announcement::TYPE_CALL_FOR_PAPERS,
            'title' => 'Call for Papers: '.fake()->words(fake()->numberBetween(3, 6), true),
            'expires_at' => fake()->dateTimeBetween('+1 month', '+6 months'),
        ]);
    }

    /**
     * Create an event announcement.
     */
    public function event(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => Announcement::TYPE_EVENT,
            'title' => fake()->randomElement(['Workshop', 'Conference', 'Seminar', 'Webinar']).': '.fake()->words(fake()->numberBetween(3, 5), true),
        ]);
    }

    /**
     * Associate with a specific journal.
     */
    public function forJournal(Journal $journal): static
    {
        return $this->state(fn (array $attributes) => [
            'journal_id' => $journal->id,
        ]);
    }

    /**
     * Associate with a specific author.
     */
    public function byAuthor(User $user): static
    {
        return $this->state(fn (array $attributes) => [
            'user_id' => $user->id,
        ]);
    }
}
