<?php

namespace Database\Factories;

use App\Models\Issue;
use App\Models\Journal;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Issue>
 */
class IssueFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Issue::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'journal_id' => Journal::factory(),
            'volume_number' => fake()->numberBetween(1, 15),
            'issue_number' => fake()->numberBetween(1, 4),
            'issue_title' => $this->generateIssueTitle(),
            'slug' => null, // Will be auto-generated by sluggable trait
            'description' => fake()->paragraphs(fake()->numberBetween(2, 4), true),
            'publication_date' => fake()->boolean(70) ? fake()->dateTimeBetween('-2 years', '+6 months') : null,
            'status' => fake()->randomElement([
                Issue::STATUS_DRAFT,
                Issue::STATUS_IN_REVIEW,
                Issue::STATUS_PUBLISHED,
                Issue::STATUS_ARCHIVED,
            ]),
            'cover_image' => fake()->boolean(60) ? 'covers/'.fake()->uuid().'.jpg' : null,
            'doi' => fake()->boolean(30) ? '10.1234/journal.v'.fake()->numberBetween(1, 15).'.i'.fake()->numberBetween(1, 4) : null,
            'theme' => fake()->boolean(80) ? $this->generateTheme() : null,
            'editorial_note' => fake()->boolean(40) ? fake()->paragraph() : null,
            'user_id' => User::factory(),
            'resolution_notes' => fake()->boolean(20) ? fake()->paragraph() : null,
        ];
    }

    /**
     * Generate realistic issue titles.
     */
    private function generateIssueTitle(): string
    {
        $titleTypes = [
            'Special Issue: '.fake()->words(fake()->numberBetween(2, 4), true),
            'Volume '.fake()->numberBetween(1, 15).', Issue '.fake()->numberBetween(1, 4),
            fake()->words(fake()->numberBetween(3, 6), true).' Edition',
            fake()->monthName().' '.fake()->year().' Issue',
            'Research in '.fake()->words(fake()->numberBetween(2, 3), true),
        ];

        return fake()->randomElement($titleTypes);
    }

    /**
     * Generate realistic themes for issues.
     */
    private function generateTheme(): string
    {
        $themes = [
            'Educational Technology',
            'Distance Learning',
            'Curriculum Development',
            'Assessment and Evaluation',
            'Teacher Training',
            'Higher Education',
            'Early Childhood Education',
            'Special Education',
            'Educational Psychology',
            'Educational Leadership',
            'STEM Education',
            'Language Learning',
            'Online Learning',
            'Educational Research Methods',
            'Learning Analytics',
            'Inclusive Education',
            'Educational Policy',
            'Student Engagement',
            'Professional Development',
            'Educational Innovation',
        ];

        return fake()->randomElement($themes);
    }

    /**
     * Indicate that the issue is in draft status.
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => Issue::STATUS_DRAFT,
            'publication_date' => null,
            'doi' => null,
        ]);
    }

    /**
     * Indicate that the issue is in review.
     */
    public function inReview(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => Issue::STATUS_IN_REVIEW,
            'publication_date' => fake()->dateTimeBetween('now', '+3 months'),
        ]);
    }

    /**
     * Indicate that the issue is published.
     */
    public function published(): static
    {
        $publicationDate = fake()->dateTimeBetween('-2 years', 'now');

        return $this->state(fn (array $attributes) => [
            'status' => Issue::STATUS_PUBLISHED,
            'publication_date' => $publicationDate,
            'doi' => '10.1234/journal.v'.fake()->numberBetween(1, 15).'.i'.fake()->numberBetween(1, 4),
            'cover_image' => 'covers/'.fake()->uuid().'.jpg',
        ]);
    }

    /**
     * Indicate that the issue is archived.
     */
    public function archived(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => Issue::STATUS_ARCHIVED,
            'publication_date' => fake()->dateTimeBetween('-5 years', '-1 year'),
            'doi' => '10.1234/journal.v'.fake()->numberBetween(1, 15).'.i'.fake()->numberBetween(1, 4),
        ]);
    }

    /**
     * Create an issue for a specific volume.
     */
    public function forVolume(int $volume): static
    {
        return $this->state(fn (array $attributes) => [
            'volume_number' => $volume,
        ]);
    }

    /**
     * Create an issue with a specific issue number.
     */
    public function withIssueNumber(int $issueNumber): static
    {
        return $this->state(fn (array $attributes) => [
            'issue_number' => $issueNumber,
        ]);
    }

    /**
     * Create an issue for a specific volume and issue number.
     */
    public function forVolumeAndIssue(int $volume, int $issueNumber): static
    {
        return $this->state(fn (array $attributes) => [
            'volume_number' => $volume,
            'issue_number' => $issueNumber,
        ]);
    }

    /**
     * Create an issue with a specific theme.
     */
    public function withTheme(string $theme): static
    {
        return $this->state(fn (array $attributes) => [
            'theme' => $theme,
            'issue_title' => 'Special Issue: '.$theme,
        ]);
    }

    /**
     * Create an issue created by a specific user.
     */
    public function createdBy(User $user): static
    {
        return $this->state(fn (array $attributes) => [
            'user_id' => $user->id,
        ]);
    }

    /**
     * Create a current year issue.
     */
    public function currentYear(): static
    {
        return $this->state(fn (array $attributes) => [
            'publication_date' => fake()->dateTimeBetween('january this year', 'december this year'),
        ]);
    }

    /**
     * Create an issue with cover image.
     */
    public function withCover(): static
    {
        return $this->state(fn (array $attributes) => [
            'cover_image' => 'covers/'.fake()->uuid().'.jpg',
        ]);
    }

    /**
     * Create an issue with DOI.
     */
    public function withDoi(): static
    {
        return $this->state(fn (array $attributes) => [
            'doi' => '10.1234/journal.v'.($attributes['volume_number'] ?? fake()->numberBetween(1, 15)).
                     '.i'.($attributes['issue_number'] ?? fake()->numberBetween(1, 4)),
        ]);
    }

    /**
     * Create a special issue.
     */
    public function specialIssue(): static
    {
        return $this->state(fn (array $attributes) => [
            'theme' => $this->generateTheme(),
            'issue_title' => 'Special Issue: '.$this->generateTheme(),
            'editorial_note' => fake()->paragraphs(fake()->numberBetween(2, 3), true),
        ]);
    }
}
