<?php

namespace Database\Factories;

use App\ManuscriptStatus;
use App\Models\Issue;
use App\Models\Journal;
use App\Models\Manuscript;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Manuscript>
 */
class ManuscriptFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Manuscript::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $submissionDate = fake()->dateTimeBetween('-2 years', 'now');
        $revisedDate = fake()->boolean(30) ? fake()->dateTimeBetween($submissionDate, 'now') : null;
        $decisionDate = fake()->boolean(60) ? fake()->dateTimeBetween($submissionDate, 'now') : null;

        return [
            'journal_id' => Journal::factory(),
            'user_id' => User::factory(),
            'issue_id' => null, // Don't auto-create issues - let seeder handle this
            'title' => fake()->sentence(fake()->numberBetween(8, 15)),
            'slug' => null, // Will be auto-generated by sluggable trait
            'authors' => $this->generateAuthors(),
            'abstract' => fake()->paragraphs(fake()->numberBetween(3, 5), true),
            'keywords' => implode(', ', fake()->words(fake()->numberBetween(3, 8))),
            'manuscript_path' => 'manuscripts/'.fake()->uuid().'.pdf',
            'status' => fake()->randomElement(ManuscriptStatus::cases()),
            'screening_status' => fake()->randomElement(['Pending', 'Passed', 'Failed']),
            'screening_comments' => fake()->boolean(40) ? fake()->paragraph() : null,
            'screened_at' => fake()->boolean(60) ? fake()->dateTimeBetween($submissionDate, 'now') : null,
            'screened_by' => fake()->boolean(60) ? User::factory() : null,
            'revision_history' => fake()->boolean(30) ? $this->generateRevisionHistory() : null,
            'revision_comments' => fake()->boolean(30) ? fake()->paragraph() : null,
            'revised_at' => $revisedDate,
            'editor_id' => fake()->boolean(80) ? User::factory() : null,
            'submission_date' => $submissionDate,
            'decision_date' => $decisionDate,
            'decision_comments' => $decisionDate ? fake()->paragraph() : null,
            'publication_date' => fake()->boolean(20) ? fake()->dateTimeBetween($submissionDate, '+1 year') : null,
            'doi' => fake()->boolean(20) ? '10.1234/journal.'.fake()->numberBetween(1000, 9999) : null,
            'volume' => fake()->boolean(20) ? fake()->numberBetween(1, 10) : null,
            'issue' => fake()->boolean(20) ? fake()->numberBetween(1, 4) : null,
            'page_range' => fake()->boolean(20) ? fake()->numberBetween(1, 200).'-'.fake()->numberBetween(201, 250) : null,
            'final_pdf_path' => fake()->boolean(20) ? 'final-manuscripts/'.fake()->uuid().'.pdf' : null,
            'final_manuscript_uploaded_at' => fake()->boolean(20) ? fake()->dateTimeBetween($submissionDate, 'now') : null,
            'author_approval_date' => fake()->boolean(15) ? fake()->dateTimeBetween($submissionDate, 'now') : null,
            'published_at' => fake()->boolean(15) ? fake()->dateTimeBetween($submissionDate, 'now') : null,
        ];
    }

    /**
     * Generate realistic author names.
     */
    private function generateAuthors(): string
    {
        $authorCount = fake()->numberBetween(1, 5);
        $authors = [];

        for ($i = 0; $i < $authorCount; $i++) {
            $authors[] = fake()->firstName().' '.fake()->lastName();
        }

        return implode(', ', $authors);
    }

    /**
     * Generate realistic revision history.
     */
    private function generateRevisionHistory(): array
    {
        $revisionCount = fake()->numberBetween(1, 3);
        $history = [];

        for ($i = 0; $i < $revisionCount; $i++) {
            $history[] = [
                'version' => $i + 1,
                'submitted_at' => fake()->dateTimeBetween('-1 year', 'now')->format('Y-m-d H:i:s'),
                'changes' => fake()->sentence(),
                'file_path' => 'manuscripts/revisions/'.fake()->uuid().'.pdf',
            ];
        }

        return $history;
    }

    /**
     * Indicate that the manuscript is submitted.
     */
    public function submitted(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ManuscriptStatus::SUBMITTED,
            'screening_status' => 'Pending',
            'decision_date' => null,
            'publication_date' => null,
            'published_at' => null,
        ]);
    }

    /**
     * Indicate that the manuscript is under review.
     */
    public function underReview(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ManuscriptStatus::UNDER_REVIEW,
            'screening_status' => 'Passed',
            'screened_at' => fake()->dateTimeBetween('-1 year', 'now'),
            'editor_id' => User::factory(),
        ]);
    }

    /**
     * Indicate that the manuscript needs revision.
     */
    public function needsRevision(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => fake()->randomElement([ManuscriptStatus::MINOR_REVISION_REQUIRED, ManuscriptStatus::MAJOR_REVISION_REQUIRED]),
            'decision_date' => fake()->dateTimeBetween('-6 months', 'now'),
            'decision_comments' => fake()->paragraph(),
            'revision_comments' => fake()->paragraph(),
        ]);
    }

    /**
     * Indicate that the manuscript is accepted.
     */
    public function accepted(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ManuscriptStatus::ACCEPTED,
            'decision_date' => fake()->dateTimeBetween('-3 months', 'now'),
            'decision_comments' => 'Manuscript accepted for publication.',
            'screening_status' => 'Passed',
        ]);
    }

    /**
     * Indicate that the manuscript is published.
     */
    public function published(): static
    {
        $publicationDate = fake()->dateTimeBetween('-1 year', 'now');
        $approvalDate = fake()->dateTimeBetween('-1 year', $publicationDate);

        return $this->state(fn (array $attributes) => [
            'status' => ManuscriptStatus::PUBLISHED,
            'publication_date' => $publicationDate,
            'published_at' => $publicationDate,
            'doi' => '10.1234/journal.'.fake()->numberBetween(1000, 9999),
            'volume' => fake()->numberBetween(1, 10),
            'issue' => fake()->numberBetween(1, 4),
            'page_range' => fake()->numberBetween(1, 200).'-'.fake()->numberBetween(201, 250),
            'final_pdf_path' => 'final-manuscripts/'.fake()->uuid().'.pdf',
            'author_approval_date' => $approvalDate,
            'issue_id' => null, // Will be set by seeder if needed
        ]);
    }

    /**
     * Indicate that the manuscript is rejected.
     */
    public function rejected(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ManuscriptStatus::REJECTED,
            'decision_date' => fake()->dateTimeBetween('-1 year', 'now'),
            'decision_comments' => fake()->paragraph(),
        ]);
    }

    /**
     * Create a manuscript with multiple revisions.
     */
    public function withRevisions(): static
    {
        return $this->state(fn (array $attributes) => [
            'revision_history' => $this->generateRevisionHistory(),
            'revised_at' => fake()->dateTimeBetween('-6 months', 'now'),
            'revision_comments' => fake()->paragraph(),
        ]);
    }

    /**
     * Create a manuscript with specific author.
     */
    public function byAuthor(User $author): static
    {
        return $this->state(fn (array $attributes) => [
            'user_id' => $author->id,
        ]);
    }

    /**
     * Create a manuscript assigned to specific editor.
     */
    public function assignedToEditor(User $editor): static
    {
        return $this->state(fn (array $attributes) => [
            'editor_id' => $editor->id,
        ]);
    }

    /**
     * Create a manuscript for specific issue.
     */
    public function forIssue(Issue $issue): static
    {
        return $this->state(fn (array $attributes) => [
            'issue_id' => $issue->id,
        ]);
    }
}
